/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DetailedResponseString,
} from '../models';
import {
    DetailedResponseStringFromJSON,
    DetailedResponseStringToJSON,
} from '../models';

/**
 * 
 */
export class ServiceMetadataControllerApi extends runtime.BaseAPI {

    /**
     * Retrieve current web service version.
     */
    async getServiceVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailedResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/version`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailedResponseStringFromJSON(jsonValue));
    }

    /**
     * Retrieve current web service version.
     */
    async getServiceVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailedResponseString> {
        const response = await this.getServiceVersionRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async pingServiceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailedResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailedResponseStringFromJSON(jsonValue));
    }

    /**
     */
    async pingService(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailedResponseString> {
        const response = await this.pingServiceRaw(initOverrides);
        return await response.value();
    }

}
