/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataPointDTO
 */
export interface DataPointDTO {
    /**
     * 
     * @type {number}
     * @memberof DataPointDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DataPointDTO
     */
    namespace?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataPointDTO
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the DataPointDTO interface.
 */
export function instanceOfDataPointDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataPointDTOFromJSON(json: any): DataPointDTO {
    return DataPointDTOFromJSONTyped(json, false);
}

export function DataPointDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPointDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'namespace': !exists(json, 'namespace') ? undefined : json['namespace'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function DataPointDTOToJSON(value?: DataPointDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'namespace': value.namespace,
        'tags': value.tags,
    };
}

