/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseListInteger
 */
export interface DetailedResponseListInteger {
    /**
     * Response data.
     * @type {Array<number>}
     * @memberof DetailedResponseListInteger
     */
    data?: Array<number>;
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseListInteger
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseListInteger interface.
 */
export function instanceOfDetailedResponseListInteger(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseListIntegerFromJSON(json: any): DetailedResponseListInteger {
    return DetailedResponseListIntegerFromJSONTyped(json, false);
}

export function DetailedResponseListIntegerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseListInteger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseListIntegerToJSON(value?: DetailedResponseListInteger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'details': ResponseDetailsToJSON(value.details),
    };
}

