/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';
import type { TravelBranchOptionDTO } from './TravelBranchOptionDTO';
import {
    TravelBranchOptionDTOFromJSON,
    TravelBranchOptionDTOFromJSONTyped,
    TravelBranchOptionDTOToJSON,
} from './TravelBranchOptionDTO';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseListTravelBranchOptionDTO
 */
export interface DetailedResponseListTravelBranchOptionDTO {
    /**
     * Response data.
     * @type {Array<TravelBranchOptionDTO>}
     * @memberof DetailedResponseListTravelBranchOptionDTO
     */
    data?: Array<TravelBranchOptionDTO>;
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseListTravelBranchOptionDTO
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseListTravelBranchOptionDTO interface.
 */
export function instanceOfDetailedResponseListTravelBranchOptionDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseListTravelBranchOptionDTOFromJSON(json: any): DetailedResponseListTravelBranchOptionDTO {
    return DetailedResponseListTravelBranchOptionDTOFromJSONTyped(json, false);
}

export function DetailedResponseListTravelBranchOptionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseListTravelBranchOptionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(TravelBranchOptionDTOFromJSON)),
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseListTravelBranchOptionDTOToJSON(value?: DetailedResponseListTravelBranchOptionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(TravelBranchOptionDTOToJSON)),
        'details': ResponseDetailsToJSON(value.details),
    };
}

