/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseString
 */
export interface DetailedResponseString {
    /**
     * Response data.
     * @type {string}
     * @memberof DetailedResponseString
     */
    data?: string;
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseString
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseString interface.
 */
export function instanceOfDetailedResponseString(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseStringFromJSON(json: any): DetailedResponseString {
    return DetailedResponseStringFromJSONTyped(json, false);
}

export function DetailedResponseStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseStringToJSON(value?: DetailedResponseString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'details': ResponseDetailsToJSON(value.details),
    };
}

