/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';
import type { TravelBranchOptionDTO } from './TravelBranchOptionDTO';
import {
    TravelBranchOptionDTOFromJSON,
    TravelBranchOptionDTOFromJSONTyped,
    TravelBranchOptionDTOToJSON,
} from './TravelBranchOptionDTO';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseListListTravelBranchOptionDTO
 */
export interface DetailedResponseListListTravelBranchOptionDTO {
    /**
     * Response data.
     * @type {Array<Array<TravelBranchOptionDTO>>}
     * @memberof DetailedResponseListListTravelBranchOptionDTO
     */
    data?: Array<Array<TravelBranchOptionDTO>>;
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseListListTravelBranchOptionDTO
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseListListTravelBranchOptionDTO interface.
 */
export function instanceOfDetailedResponseListListTravelBranchOptionDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseListListTravelBranchOptionDTOFromJSON(json: any): DetailedResponseListListTravelBranchOptionDTO {
    return DetailedResponseListListTravelBranchOptionDTOFromJSONTyped(json, false);
}

export function DetailedResponseListListTravelBranchOptionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseListListTravelBranchOptionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseListListTravelBranchOptionDTOToJSON(value?: DetailedResponseListListTravelBranchOptionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'details': ResponseDetailsToJSON(value.details),
    };
}

