/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataPointDTO } from './DataPointDTO';
import {
    DataPointDTOFromJSON,
    DataPointDTOFromJSONTyped,
    DataPointDTOToJSON,
} from './DataPointDTO';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseMapIntegerListDataPointDTO
 */
export interface DetailedResponseMapIntegerListDataPointDTO {
    /**
     * Response data.
     * @type {{ [key: string]: Array<DataPointDTO>; }}
     * @memberof DetailedResponseMapIntegerListDataPointDTO
     */
    data?: { [key: string]: Array<DataPointDTO>; };
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseMapIntegerListDataPointDTO
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseMapIntegerListDataPointDTO interface.
 */
export function instanceOfDetailedResponseMapIntegerListDataPointDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseMapIntegerListDataPointDTOFromJSON(json: any): DetailedResponseMapIntegerListDataPointDTO {
    return DetailedResponseMapIntegerListDataPointDTOFromJSONTyped(json, false);
}

export function DetailedResponseMapIntegerListDataPointDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseMapIntegerListDataPointDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseMapIntegerListDataPointDTOToJSON(value?: DetailedResponseMapIntegerListDataPointDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'details': ResponseDetailsToJSON(value.details),
    };
}

