/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelDTO } from './ModelDTO';
import {
    ModelDTOFromJSON,
    ModelDTOFromJSONTyped,
    ModelDTOToJSON,
} from './ModelDTO';
import type { ResponseDetails } from './ResponseDetails';
import {
    ResponseDetailsFromJSON,
    ResponseDetailsFromJSONTyped,
    ResponseDetailsToJSON,
} from './ResponseDetails';

/**
 * Base generic detailed response.
 * @export
 * @interface DetailedResponseModelDTO
 */
export interface DetailedResponseModelDTO {
    /**
     * 
     * @type {ModelDTO}
     * @memberof DetailedResponseModelDTO
     */
    data?: ModelDTO;
    /**
     * 
     * @type {ResponseDetails}
     * @memberof DetailedResponseModelDTO
     */
    details?: ResponseDetails;
}

/**
 * Check if a given object implements the DetailedResponseModelDTO interface.
 */
export function instanceOfDetailedResponseModelDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetailedResponseModelDTOFromJSON(json: any): DetailedResponseModelDTO {
    return DetailedResponseModelDTOFromJSONTyped(json, false);
}

export function DetailedResponseModelDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedResponseModelDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ModelDTOFromJSON(json['data']),
        'details': !exists(json, 'details') ? undefined : ResponseDetailsFromJSON(json['details']),
    };
}

export function DetailedResponseModelDTOToJSON(value?: DetailedResponseModelDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ModelDTOToJSON(value.data),
        'details': ResponseDetailsToJSON(value.details),
    };
}

