/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response details.
 * @export
 * @interface ResponseDetails
 */
export interface ResponseDetails {
    /**
     * 
     * @type {string}
     * @memberof ResponseDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseDetails
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseDetails
     */
    notes?: Array<string>;
}

/**
 * Check if a given object implements the ResponseDetails interface.
 */
export function instanceOfResponseDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseDetailsFromJSON(json: any): ResponseDetails {
    return ResponseDetailsFromJSONTyped(json, false);
}

export function ResponseDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function ResponseDetailsToJSON(value?: ResponseDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'notes': value.notes,
    };
}

