/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainingSession
 */
export interface TrainingSession {
    /**
     * 
     * @type {Date}
     * @memberof TrainingSession
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof TrainingSession
     */
    msTaken?: number;
}

/**
 * Check if a given object implements the TrainingSession interface.
 */
export function instanceOfTrainingSession(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TrainingSessionFromJSON(json: any): TrainingSession {
    return TrainingSessionFromJSONTyped(json, false);
}

export function TrainingSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'msTaken': !exists(json, 'msTaken') ? undefined : json['msTaken'],
    };
}

export function TrainingSessionToJSON(value?: TrainingSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'msTaken': value.msTaken,
    };
}

