/* tslint:disable */
/* eslint-disable */
/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataPointDTO } from './DataPointDTO';
import {
    DataPointDTOFromJSON,
    DataPointDTOFromJSONTyped,
    DataPointDTOToJSON,
} from './DataPointDTO';

/**
 * Response data.
 * @export
 * @interface TravelBranchOptionDTO
 */
export interface TravelBranchOptionDTO {
    /**
     * 
     * @type {DataPointDTO}
     * @memberof TravelBranchOptionDTO
     */
    option?: DataPointDTO;
    /**
     * 
     * @type {DataPointDTO}
     * @memberof TravelBranchOptionDTO
     */
    edge?: DataPointDTO;
}

/**
 * Check if a given object implements the TravelBranchOptionDTO interface.
 */
export function instanceOfTravelBranchOptionDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TravelBranchOptionDTOFromJSON(json: any): TravelBranchOptionDTO {
    return TravelBranchOptionDTOFromJSONTyped(json, false);
}

export function TravelBranchOptionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelBranchOptionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'option': !exists(json, 'option') ? undefined : DataPointDTOFromJSON(json['option']),
        'edge': !exists(json, 'edge') ? undefined : DataPointDTOFromJSON(json['edge']),
    };
}

export function TravelBranchOptionDTOToJSON(value?: TravelBranchOptionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'option': DataPointDTOToJSON(value.option),
        'edge': DataPointDTOToJSON(value.edge),
    };
}

